//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class sFramework_sNetworkInterfaceWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(sFramework.sNetworkInterface), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("createAccount", createAccount);
		L.RegFunction("login", login);
		L.RegFunction("sendMsg2Server", sendMsg2Server);
		L.RegFunction("selAvatar", selAvatar);
		L.RegFunction("createAvatar", createAvatar);
		L.RegFunction("delAvatar", delAvatar);
		L.RegFunction("getAvatarList", getAvatarList);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", Lua_ToString);
		L.RegVar("instance", get_instance, set_instance);
		L.RegVar("selAvatarDBID", get_selAvatarDBID, set_selAvatarDBID);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int createAccount(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 5);
			sFramework.sNetworkInterface obj = (sFramework.sNetworkInterface)ToLua.CheckObject(L, 1, typeof(sFramework.sNetworkInterface));
			string arg0 = ToLua.CheckString(L, 2);
			string arg1 = ToLua.CheckString(L, 3);
			string arg2 = ToLua.CheckString(L, 4);
			string arg3 = ToLua.CheckString(L, 5);
			obj.createAccount(arg0, arg1, arg2, arg3);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int login(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 5);
			sFramework.sNetworkInterface obj = (sFramework.sNetworkInterface)ToLua.CheckObject(L, 1, typeof(sFramework.sNetworkInterface));
			string arg0 = ToLua.CheckString(L, 2);
			string arg1 = ToLua.CheckString(L, 3);
			string arg2 = ToLua.CheckString(L, 4);
			string arg3 = ToLua.CheckString(L, 5);
			obj.login(arg0, arg1, arg2, arg3);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int sendMsg2Server(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			sFramework.sNetworkInterface obj = (sFramework.sNetworkInterface)ToLua.CheckObject(L, 1, typeof(sFramework.sNetworkInterface));
			string arg0 = ToLua.CheckString(L, 2);
			object[] arg1 = ToLua.ToParamsObject(L, 3, count - 2);
			obj.sendMsg2Server(arg0, arg1);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int selAvatar(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			sFramework.sNetworkInterface obj = (sFramework.sNetworkInterface)ToLua.CheckObject(L, 1, typeof(sFramework.sNetworkInterface));
			ulong arg0 = (ulong)LuaDLL.luaL_checknumber(L, 2);
			string arg1 = ToLua.CheckString(L, 3);
			string arg2 = ToLua.CheckString(L, 4);
			obj.selAvatar(arg0, arg1, arg2);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int createAvatar(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 5);
			sFramework.sNetworkInterface obj = (sFramework.sNetworkInterface)ToLua.CheckObject(L, 1, typeof(sFramework.sNetworkInterface));
			byte arg0 = (byte)LuaDLL.luaL_checknumber(L, 2);
			string arg1 = ToLua.CheckString(L, 3);
			string arg2 = ToLua.CheckString(L, 4);
			string arg3 = ToLua.CheckString(L, 5);
			obj.createAvatar(arg0, arg1, arg2, arg3);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int delAvatar(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			sFramework.sNetworkInterface obj = (sFramework.sNetworkInterface)ToLua.CheckObject(L, 1, typeof(sFramework.sNetworkInterface));
			string arg0 = ToLua.CheckString(L, 2);
			string arg1 = ToLua.CheckString(L, 3);
			string arg2 = ToLua.CheckString(L, 4);
			obj.delAvatar(arg0, arg1, arg2);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int getAvatarList(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			sFramework.sNetworkInterface obj = (sFramework.sNetworkInterface)ToLua.CheckObject(L, 1, typeof(sFramework.sNetworkInterface));
			System.Collections.Generic.Dictionary<ulong,sAvatarList> o = obj.getAvatarList();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Lua_ToString(IntPtr L)
	{
		object obj = ToLua.ToObject(L, 1);

		if (obj != null)
		{
			LuaDLL.lua_pushstring(L, obj.ToString());
		}
		else
		{
			LuaDLL.lua_pushnil(L);
		}

		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_instance(IntPtr L)
	{
		try
		{
			ToLua.Push(L, sFramework.sNetworkInterface.instance);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_selAvatarDBID(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			sFramework.sNetworkInterface obj = (sFramework.sNetworkInterface)o;
			ulong ret = obj.selAvatarDBID;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index selAvatarDBID on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_instance(IntPtr L)
	{
		try
		{
			sFramework.sNetworkInterface arg0 = (sFramework.sNetworkInterface)ToLua.CheckUnityObject(L, 2, typeof(sFramework.sNetworkInterface));
			sFramework.sNetworkInterface.instance = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_selAvatarDBID(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			sFramework.sNetworkInterface obj = (sFramework.sNetworkInterface)o;
			ulong arg0 = (ulong)LuaDLL.luaL_checknumber(L, 2);
			obj.selAvatarDBID = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index selAvatarDBID on a nil value" : e.Message);
		}
	}
}

